client/JillDemo.js
=> Jill trial branch push

demo.js
=> soheila created demo.js

client/JillDemo.js, demo.js
=> Starting point with BoilerPlate - removed trial files

.travis.yml, client/components/auth-form.js, client/components/navbar.js, demo.js, package-lock.json, package.json, public/index.html, server/db/models/author.js, server/db/models/book.js, server/db/models/index.js, server/db/models/orderItem.js, server/db/models/review.js, server/db/models/sale.js, server/db/models/user.js, tests/client/components/user-home.spec.js, tests/client/store/user.spec.js, tests/script/seed.spec.js, tests/server/api/users.spec.js, tests/server/db/models/user.spec.js
=> Updated to create test folder and move all tests there - Gayathri

client/components/navbar.js, public/style.css, seed.js, server/api/books.js, server/api/index.js, server/db/models/review.js, server/db/models/sale.js
=> Jill branch

server/api/books.js
=> Single book api path

script/seed.js
=> seed file working

package.json, script/seed.js, server/db/db.js, server/db/models/index.js, tests/client/store/user.spec.js
=> updated test files and minor changes to associations and seed file

client/components/SingleBook.js, client/components/books-query.js, client/reducers/book.js
=> updated reducer logic for getting all and queried books, updated books-query component

client/components/SingleBook.js, script/seed.js, server/api/genres.js, server/api/index.js
=> Katie branch

client/components/allBooks.js, client/routes.js
=> working code for start day 3

client/components/SingleAuthor.js, client/components/allAuthors.js, client/reducers/author.js, client/routes.js, server/api/authors.js
=> Single Authors

client/components/books-query.js, server/api/authors.js, server/api/books.js, server/api/genres.js
=> search bar working fro all searches

client/components/SingleBook.js, client/components/allAuthors.js, client/components/cart.js, client/reducers/cart.js, client/reducers/index.js, client/routes.js, public/style.css
=> Soheila branch

server/db/models/orderBook.js
=> Added soldOutOrNot instance method to OrderBook model

client/components/Review.js, script/seed.js, server/api/index.js, server/api/reviews.js, server/db/models/index.js, server/db/models/user.js
=> Added Reviews to seed file and api routes

client/components/navbar.js, client/components/pastOrders.js, client/reducers/author.js, client/reducers/index.js, client/reducers/orders.js, client/routes.js, server/api/index.js, server/api/orders.js
=> past orders component for users working

client/components/AddReview.js, client/components/Review.js, client/components/ReviewForm.js, client/components/SingleBook.js, client/reducers/review.js
=> Reviews need a little care, put no errors

client/components/AddReview.js, client/components/Review.js, client/components/SingleBook.js, server/api/books.js
=> Fixed link in SingleBooks component

client/components/UserCart.js, client/reducers/cart.js, client/reducers/orders.js, server/api/index.js, server/api/orderBooks.js, server/api/orders.js
=> checkout completed

client/reducers/cart.js, server/api/orders.js
=> WORKING CODE END OF DAY

client/components/AddReview.js, client/components/Review.js, client/components/SingleBook.js, client/reducers/book.js, server/api/books.js
=> Review and AddReview is finished

script/seed.js
=> Basic tests working (the ones from boilermaker)

client/components/AddReview.js, client/components/Review.js, client/components/SingleBook.js, package-lock.json, package.json, public/index.html, public/style.css, script/seed.js, server/db/models/review.js
=> Okay now I'm really done with reviews

public/style.css
=> ready to deploy

client/components/Checkout.js
=> post url changes

package-lock.json, package.json
based on security vulnerability notes
=> upgrades to address security vulnerabilities
